services:
  chemistry:
    build:
      context: ./services/chemistry

    container_name: mdp-chemistry

    ports:
      - "8001:8000"

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"
        ]
      interval: 10s
      timeout: 5s
      retries: 3