services:
  gateway:
    build:
      context: ./services/gateway

    container_name: mdp-gateway

    ports:
      - "8000:8000"

    environment:
      CHEMISTRY_SERVICE_URL: http://chemistry:8000
      PREDICTION_SERVICE_URL: http://prediction:8000

    depends_on:
      chemistry:
        condition: service_healthy
      prediction:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"
        ]
      interval: 10s
      timeout: 5s
      retries: 3


  chemistry:
    build:
      context: .
      dockerfile: services/chemistry/Dockerfile

    container_name: mdp-chemistry

    ports:
      - "8001:8000"

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"
        ]
      interval: 10s
      timeout: 5s
      retries: 3


  prediction:
    build:
      context: ./services/prediction

    container_name: mdp-prediction

    ports:
      - "8002:8000"

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"
        ]
      interval: 10s
      timeout: 5s
      retries: 3